### ISSUE TITLE
Замечания к коду

### ISSUE THREAD

**Issue by AlexCr4ckPentest** [DataSC3/No-BlackM#2]
Дружище :)
в следующи раз пиши четко-структурированный и понятный код!
такой код вообще не в какие рамки не лезет! то, что ты написал, уж прости, но это ужас!!!
а постараюсь переделать это, открою pull request, а ты уж будь добр - прими его потом :D

**Comment by NurlanTanatar** [comment]
Здраствуйте, большое спасибо за помощь!
Форкнул проект у одного человека недавно 
хотел сам просмотреть код и отрефакторить XD
Спасибо в любом случае)
